[project]
name = "diffusion"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "diffusers>=0.1.0",
    "importlib-metadata>=9.0.0",
    "ipykernel>=7.3.0",
    "matplotlib>=3.11.1",
    "opencv-python>=5.0.0.93",
    "torch>=2.13.0",
    "torchvision>=0.28.0",
]
